module Mirrors
  module YARVData
    INSTRUCTION_NUMBERS = {
      nop:                          0,
      getlocal:                     1,
      setlocal:                     2,
      getspecial:                   3,
      setspecial:                   4,
      getinstancevariable:          5,
      setinstancevariable:          6,
      getclassvariable:             7,
      setclassvariable:             8,
      getconstant:                  9,
      getpackagemember:            10,
      setconstant:                 11,
      getglobal:                   12,
      setglobal:                   13,
      putnil:                      14,
      putself:                     15,
      putobject:                   16,
      putspecialobject:            17,
      putiseq:                     18,
      putstring:                   19,
      concatstrings:               20,
      tostring:                    21,
      freezestring:                22,
      toregexp:                    23,
      newarray:                    24,
      duparray:                    25,
      expandarray:                 26,
      concatarray:                 27,
      splatarray:                  28,
      newhash:                     29,
      newrange:                    30,
      pop:                         31,
      dup:                         32,
      dupn:                        33,
      swap:                        34,
      reverse:                     35,
      reput:                       36,
      topn:                        37,
      setn:                        38,
      adjuststack:                 39,
      defined:                     40,
      checkmatch:                  41,
      checkkeyword:                42,
      trace:                       43,
      defineclass:                 44,
      send:                        45,
      opt_str_freeze:              46,
      opt_newarray_max:            47,
      opt_newarray_min:            48,
      opt_send_without_block:      49,
      invokesuper:                 50,
      invokeblock:                 51,
      leave:                       52,
      throw:                       53,
      jump:                        54,
      branchif:                    55,
      branchunless:                56,
      branchnil:                   57,
      getinlinecache:              58,
      setinlinecache:              59,
      once:                        60,
      opt_case_dispatch:           61,
      opt_plus:                    62,
      opt_minus:                   63,
      opt_mult:                    64,
      opt_div:                     65,
      opt_mod:                     66,
      opt_eq:                      67,
      opt_neq:                     68,
      opt_lt:                      69,
      opt_le:                      70,
      opt_gt:                      71,
      opt_ge:                      72,
      opt_ltlt:                    73,
      opt_aref:                    74,
      opt_aset:                    75,
      opt_aset_with:               76,
      opt_aref_with:               77,
      opt_length:                  78,
      opt_size:                    79,
      opt_empty_p:                 80,
      opt_succ:                    81,
      opt_not:                     82,
      opt_regexpmatch1:            83,
      opt_regexpmatch2:            84,
      opt_call_c_function:         85,
      bitblt:                      86,
      answer:                      87,
      getlocal_OP__WC__0:          88,
      getlocal_OP__WC__1:          89,
      setlocal_OP__WC__0:          90,
      setlocal_OP__WC__1:          91,
      putobject_OP_INT2FIX_O_0_C_: 92,
      putobject_OP_INT2FIX_O_1_C_: 93,
    }.freeze

    OPERAND_INFO = [
      [],
      [:lindex, :num],
      [:lindex, :num],
      [:num, :num],
      [:num],
      [:id, :ic],
      [:id, :ic],
      [:id],
      [:id],
      [:id],
      [:id],
      [:id],
      [:gentry],
      [:gentry],
      [],
      [],
      [:value],
      [:num],
      [:iseq],
      [:value],
      [:num],
      [],
      [:value],
      [:num, :num],
      [:num],
      [:value],
      [:num, :num],
      [],
      [:value],
      [:num],
      [:num],
      [],
      [],
      [:num],
      [],
      [:num],
      [],
      [:num],
      [:num],
      [:num],
      [:num, :value, :value],
      [:num],
      [:lindex, :num],
      [:num],
      [:id, :iseq, :num],
      [:callinfo, :callcache, :iseq],
      [:value],
      [:num],
      [:num],
      [:callinfo, :callcache],
      [:callinfo, :callcache, :iseq],
      [:callinfo],
      [],
      [:num],
      [:offset],
      [:offset],
      [:offset],
      [:offset],
      [:offset, :ic],
      [:ic],
      [:iseq, :ic],
      [:cdhash, :offset],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache, :callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache, :value],
      [:callinfo, :callcache, :value],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:callinfo, :callcache],
      [:value],
      [:callinfo, :callcache],
      [:funcptr],
      [],
      [],
      [:lindex],
      [:lindex],
      [:lindex],
      [:lindex],
      [],
      [],
    ].freeze

    LENGTH_INFO = [
      1,
      3,
      3,
      3,
      2,
      3,
      3,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      1,
      2,
      3,
      2,
      2,
      3,
      1,
      2,
      2,
      2,
      1,
      1,
      2,
      1,
      2,
      1,
      2,
      2,
      2,
      4,
      2,
      3,
      2,
      4,
      4,
      2,
      2,
      2,
      3,
      4,
      2,
      1,
      2,
      2,
      2,
      2,
      2,
      3,
      2,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      5,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      3,
      3,
      3,
      3,
      2,
      3,
      2,
      1,
      1,
      2,
      2,
      2,
      2,
      1,
      1,
    ].freeze

    STACK_PUSH_NUM_INFO = [
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      1,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      2,
      1,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
    ].freeze

    STACK_INCREASE = [
      0,
      1,
      -1,
      1,
      -1,
      1,
      -1,
      1,
      -1,
      0,
      0,
      -2,
      1,
      -1,
      1,
      1,
      1,
      1,
      1,
      1,
      :one_minus_op_0,
      0,
      0,
      :one_minus_op_1,
      :one_minus_op_0,
      1,
      :expandarray,
      -1,
      0,
      :one_minus_op_0,
      -1,
      -1,
      1,
      :op_0,
      0,
      0,
      0,
      1,
      0,
      :zero_minus_op_0,
      0,
      -1,
      1,
      0,
      -1,
      :send,
      1,
      :one_minus_op_0,
      :one_minus_op_0,
      :opt_send_without_block,
      :invokesuper,
      :invokeblock,
      0,
      0,
      0,
      -1,
      -1,
      -1,
      1,
      0,
      1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -2,
      -1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      -1,
      0,
      1,
      1,
      1,
      1,
      -1,
      -1,
      1,
      1,
    ].freeze

  end
end
