module Mirrors
  module ISeq
    module YARVData
      INSTRUCTION_NUMBERS = {
        nop:                          0,
        getlocal:                     1,
        setlocal:                     2,
        getspecial:                   3,
        setspecial:                   4,
        getinstancevariable:          5,
        setinstancevariable:          6,
        getclassvariable:             7,
        setclassvariable:             8,
        getconstant:                  9,
        setconstant:                 10,
        getglobal:                   11,
        setglobal:                   12,
        putnil:                      13,
        putself:                     14,
        putobject:                   15,
        putspecialobject:            16,
        putiseq:                     17,
        putstring:                   18,
        concatstrings:               19,
        tostring:                    20,
        freezestring:                21,
        toregexp:                    22,
        newarray:                    23,
        duparray:                    24,
        expandarray:                 25,
        concatarray:                 26,
        splatarray:                  27,
        newhash:                     28,
        newrange:                    29,
        pop:                         30,
        dup:                         31,
        dupn:                        32,
        swap:                        33,
        reverse:                     34,
        reput:                       35,
        topn:                        36,
        setn:                        37,
        adjuststack:                 38,
        defined:                     39,
        checkmatch:                  40,
        checkkeyword:                41,
        trace:                       42,
        defineclass:                 43,
        send:                        44,
        opt_str_freeze:              45,
        opt_send_without_block:      46,
        invokesuper:                 47,
        invokeblock:                 48,
        leave:                       49,
        throw:                       50,
        jump:                        51,
        branchif:                    52,
        branchunless:                53,
        branchnil:                   54,
        getinlinecache:              55,
        setinlinecache:              56,
        once:                        57,
        opt_case_dispatch:           58,
        opt_plus:                    59,
        opt_minus:                   60,
        opt_mult:                    61,
        opt_div:                     62,
        opt_mod:                     63,
        opt_eq:                      64,
        opt_neq:                     65,
        opt_lt:                      66,
        opt_le:                      67,
        opt_gt:                      68,
        opt_ge:                      69,
        opt_ltlt:                    70,
        opt_aref:                    71,
        opt_aset:                    72,
        opt_aset_with:               73,
        opt_aref_with:               74,
        opt_length:                  75,
        opt_size:                    76,
        opt_empty_p:                 77,
        opt_succ:                    78,
        opt_not:                     79,
        opt_regexpmatch1:            80,
        opt_regexpmatch2:            81,
        opt_call_c_function:         82,
        bitblt:                      83,
        answer:                      84,
        getlocal_OP__WC__0:          85,
        getlocal_OP__WC__1:          86,
        setlocal_OP__WC__0:          87,
        setlocal_OP__WC__1:          88,
        putobject_OP_INT2FIX_O_0_C_: 89,
        putobject_OP_INT2FIX_O_1_C_: 90,
      }.freeze

      OPERAND_INFO = [
        [],
        [:lindex, :num],
        [:lindex, :num],
        [:num, :num],
        [:num],
        [:id, :ic],
        [:id, :ic],
        [:id],
        [:id],
        [:id],
        [:id],
        [:gentry],
        [:gentry],
        [],
        [],
        [:value],
        [:num],
        [:iseq],
        [:value],
        [:num],
        [],
        [:value],
        [:num, :num],
        [:num],
        [:value],
        [:num, :num],
        [],
        [:value],
        [:num],
        [:num],
        [],
        [],
        [:num],
        [],
        [:num],
        [],
        [:num],
        [:num],
        [:num],
        [:num, :value, :value],
        [:num],
        [:lindex, :num],
        [:num],
        [:id, :iseq, :num],
        [:callinfo, :callcache, :iseq],
        [:value],
        [:callinfo, :callcache],
        [:callinfo, :callcache, :iseq],
        [:callinfo],
        [],
        [:num],
        [:offset],
        [:offset],
        [:offset],
        [:offset],
        [:offset, :ic],
        [:ic],
        [:iseq, :ic],
        [:cdhash, :offset],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache, :callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache, :value],
        [:callinfo, :callcache, :value],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:callinfo, :callcache],
        [:value],
        [:callinfo, :callcache],
        [:funcptr],
        [],
        [],
        [:lindex],
        [:lindex],
        [:lindex],
        [:lindex],
        [],
        [],
      ].freeze

      LENGTH_INFO = [
        1,
        3,
        3,
        3,
        2,
        3,
        3,
        2,
        2,
        2,
        2,
        2,
        2,
        1,
        1,
        2,
        2,
        2,
        2,
        2,
        1,
        2,
        3,
        2,
        2,
        3,
        1,
        2,
        2,
        2,
        1,
        1,
        2,
        1,
        2,
        1,
        2,
        2,
        2,
        4,
        2,
        3,
        2,
        4,
        4,
        2,
        3,
        4,
        2,
        1,
        2,
        2,
        2,
        2,
        2,
        3,
        2,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        5,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        4,
        4,
        3,
        3,
        3,
        3,
        3,
        2,
        3,
        2,
        1,
        1,
        2,
        2,
        2,
        2,
        1,
        1,
      ].freeze

      STACK_PUSH_NUM_INFO = [
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        2,
        1,
        2,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
      ].freeze

      STACK_INCREASE = [
        0,
        1,
        -1,
        1,
        -1,
        1,
        -1,
        1,
        -1,
        0,
        -2,
        1,
        -1,
        1,
        1,
        1,
        1,
        1,
        1,
        :one_minus_op_0,
        0,
        0,
        :one_minus_op_1,
        :one_minus_op_0,
        1,
        :expandarray,
        -1,
        0,
        :one_minus_op_0,
        -1,
        -1,
        1,
        :op_0,
        0,
        0,
        0,
        1,
        0,
        :zero_minus_op_0,
        0,
        -1,
        1,
        0,
        -1,
        :send,
        1,
        :opt_send_without_block,
        :invokesuper,
        :invokeblock,
        0,
        0,
        0,
        -1,
        -1,
        -1,
        1,
        0,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -2,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        1,
        1,
        1,
        1,
        -1,
        -1,
        1,
        1,
      ].freeze
    end
  end
end
